# Generated by Django 3.1.2 on 2021-04-25 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Content', models.TextField()),
                ('Date_published', models.DateTimeField(blank=True, null=True)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=200)),
                ('comment_text', models.TextField()),
                ('Date_commented', models.DateTimeField(blank=True, null=True)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Comment', to='myBlog.blogposts')),
            ],
        ),
    ]
