# Generated by Django 3.1.2 on 2021-04-27 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='Date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
