# Generated by Django 3.1.2 on 2021-05-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0006_auto_20210512_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
