# Generated by Django 3.1.2 on 2021-05-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0007_auto_20210512_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
